name: 'add to project'

on: 
  workflow_call:
    inputs:
      project-number:
        required: true
        type: string
    secrets:
      ISSUE_PR_RW_TOKEN:
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.ISSUE_PR_RW_TOKEN }}

jobs:
  add_to_project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: Senzing/github-action-add-issue-to-project@main
        with:
          project: "https://github.com/users/kernelsam/projects/${{inputs.project-number}}"