---

name: 'add to project'

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      project-number:
        required: true
        type: string
      classic:
        required: true
        type: boolean
        default: true
    secrets:
      PROJECT_RW_TOKEN:
        required: true

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ ! inputs.classic }}
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: "https://github.com/users/kernelsam/projects/${{inputs.project-number}}"
          github-token: ${{ env.PROJECT_RW_TOKEN }} # requires [project], [read:project] classic access token

  add-to-classic-project:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.classic }}
        run: echo "classic"
