name: 'dependabot approve and merge patch version prs'

on: 
  workflow_call:
    inputs:
      enable-dependabot-automation:
        required: false
        type: boolean
    secrets:
      CODEOWNER_PR_APPROVAL_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-approve-and-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve patch version PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: |
          gh pr review --approve "$PR_URL" -b "I'm **approving** this pull request because **it includes a patch update**"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.CODEOWNER_PR_APPROVAL_TOKEN }}
      - name: Auto merge patch version PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
