---

name: 'gofmt'

on: [workflow_call]

permissions:
  contents: read

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: gofmt
        run: |
          gofmt_out="$(gofmt -s -l .)"
          if [ -n "${gofmt_out}" ]; then
            echo "[ERROR] Files failing gofmt: "
            echo "${gofmt_out}"
            exit 1;
          else
            echo "[INFO] gofmt check passed."
          fi
