---

name: 'shellcheck'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_call:
    inputs:
      enable-shellcheck:
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  runShellCheck:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: ${{ inputs.enable-shellcheck }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Run ShellCheck
        run: |
          echo "[INFO] shellcheck version: $(shellcheck --version)"

          ###############################################
          # disable exit on error to allow shellcheck 
          # to run against all files
          ###############################################
          set +e

          declare -i status=0

          while IFS= read -r -d '' file
          do 
            shellcheck --format=gcc "$file";
            status+=$?
          done <   <(find . -type f -name "*.sh")

          echo "[INFO] Exit status is: ${status}"
          exit ${status}