name: 'shellcheck'

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_call:
    inputs:
      enable-shellcheck:
        required: false
        type: boolean


permissions:
  contents: read

jobs:
  runShellCheck:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: ${{ inputs.enable-shellcheck }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Run ShellCheck
        run: |
          echo "[INFO] shellcheck version: $(shellcheck --version)"
          for file in $(find . -type f -name "*.sh"); 
            do shellcheck --format=gcc $file; 
          done;